# Generated by Django 4.1.7 on 2023-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_order_id', models.CharField(max_length=100, verbose_name='主订单编号')),
                ('tm_order_sub_id', models.CharField(max_length=100, verbose_name='子订单编号')),
                ('tm_sku_name', models.CharField(max_length=100, verbose_name='标题')),
                ('numm', models.CharField(max_length=100, verbose_name='购买数量')),
                ('option', models.CharField(max_length=100, verbose_name='商品属性')),
                ('buy_sku_name', models.CharField(max_length=100, verbose_name='入货品')),
                ('sku_cost_price', models.IntegerField(max_length=100, verbose_name='入货价')),
                ('customer_paid', models.CharField(max_length=100, verbose_name='买家应付货款')),
                ('tm_order_create_time', models.DateTimeField(max_length=100, verbose_name='订单创建时间_x')),
                ('tm_order_payment_time', models.DateTimeField(max_length=100, verbose_name='订单付款时间')),
                ('ali_order_id', models.CharField(max_length=100, verbose_name='Partner_transaction_id')),
                ('ali_id', models.CharField(max_length=100, verbose_name='Transaction_id')),
                ('ali_usd_amount', models.FloatField(max_length=100, verbose_name='Amount')),
                ('ali_cny_amount', models.CharField(max_length=100, verbose_name='Rmb_amount')),
                ('ali_usd_fee', models.FloatField(max_length=100, verbose_name='Fee')),
                ('ali_usd_refund', models.FloatField(max_length=100, verbose_name='Refund')),
                ('ali_usd_settlement', models.FloatField(max_length=100, verbose_name='Settlement')),
                ('ali_cny_settlement', models.CharField(max_length=100, verbose_name='Rmb_settlement')),
                ('ali_currency', models.CharField(max_length=100, verbose_name='Currency')),
                ('ali_rate', models.FloatField(max_length=100, verbose_name='Rate')),
                ('ali_payment_time', models.DateTimeField(max_length=100, verbose_name='Payment_time')),
                ('ali_settlement_time', models.DateTimeField(max_length=100, verbose_name='Settlement_time')),
                ('ali_type', models.CharField(max_length=100, verbose_name='Type')),
                ('tm_order_status', models.CharField(max_length=100, verbose_name='订单状态')),
                ('tm_close_reason', models.CharField(max_length=100, verbose_name='订单关闭原因')),
                ('tm_order_confirm_time', models.DateTimeField(max_length=100, verbose_name='确认收货时间')),
                ('order_platform', models.CharField(max_length=100, verbose_name='订单源')),
                ('order_channel', models.CharField(max_length=100, verbose_name='订单出处')),
                ('order_mark', models.CharField(max_length=100, verbose_name='mark')),
                ('sku_usd_price', models.FloatField(max_length=100, verbose_name='单SKU价格USD')),
                ('sku_proportion', models.FloatField(max_length=100, verbose_name='占比')),
                ('sku_usd_fee', models.FloatField(max_length=100, verbose_name='单个SKU的Fee')),
                ('sku_usd_refund', models.FloatField(max_length=100, verbose_name='SKU退款金额')),
                ('sku_usd_settlement', models.FloatField(max_length=100, verbose_name='支付宝最终入账')),
                ('order_cost_price', models.CharField(max_length=100, verbose_name='订单成本价')),
                ('korean_rate', models.FloatField(max_length=100, verbose_name='rate2')),
                ('sku_krw_settlement', models.IntegerField(max_length=100, verbose_name='최종 입금 금액 KRW')),
                ('sku_krw_net_income', models.IntegerField(max_length=100, verbose_name='수익 KRW')),
            ],
            options={
                'db_table': 'tmalloms',
                'managed': True,
            },
        ),
    ]
