# Generated by Django 4.1.7 on 2023-03-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skulist',
            name='ali_cny_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rmb_amount'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_cny_settlement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rmb_settlement'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_currency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction_id'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partner_transaction_id'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_payment_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='Payment_time'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_rate',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_settlement_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='Settlement_time'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_usd_amount',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_usd_fee',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_usd_refund',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Refund'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='ali_usd_settlement',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Settlement'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='buy_sku_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='入货品'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='customer_paid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='买家应付货款'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='korean_rate',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='rate2'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='numm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='购买数量'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品属性'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='order_channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单出处'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='order_cost_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单成本价'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='order_mark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='order_platform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单源'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_cost_price',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='入货价'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_krw_net_income',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='수익 KRW'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_krw_settlement',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='최종 입금 금액 KRW'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_proportion',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='占比'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_usd_fee',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='单个SKU的Fee'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_usd_price',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='单SKU价格USD'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_usd_refund',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='SKU退款金额'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='sku_usd_settlement',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='支付宝最终入账'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_close_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单关闭原因'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_order_confirm_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='确认收货时间'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_order_create_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='订单创建时间_x'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主订单编号'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_order_payment_time',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='订单付款时间'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_order_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_order_sub_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='子订单编号'),
        ),
        migrations.AlterField(
            model_name='skulist',
            name='tm_sku_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
    ]
